# Generated by Django 6.0.8 on 2026-09-11 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_discount_amount_order_packing_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soft_deleted', models.IntegerField(default=0, help_text='0 = Active, 1 = Soft Deleted')),
                ('name', models.CharField(help_text='Transport or Logistics Agency Name', max_length=150, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Contact Phone / Mobile', max_length=30, null=True)),
                ('contact_person', models.CharField(blank=True, help_text='Booking Agent / Driver / Manager', max_length=100, null=True)),
                ('vehicle_number', models.CharField(blank=True, help_text='Vehicle / Truck / Lorry No.', max_length=50, null=True)),
                ('destination_notes', models.CharField(blank=True, help_text='Routes covered / Hub locations', max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transports', to='core.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='transport',
            field=models.ForeignKey(blank=True, help_text='Default preferred transport for shipping', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='core.transport'),
        ),
        migrations.AddField(
            model_name='order',
            name='transport',
            field=models.ForeignKey(blank=True, help_text='Assigned transport carrier for this order shipment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.transport'),
        ),
    ]
