# Generated by Django 6.0.8 on 2026-09-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_transport_customer_transport_order_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='custom_gst_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom GST rate percentage applied to the order', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='gst_enabled',
            field=models.BooleanField(default=True, help_text='Whether GST is applied and shown on the PDF invoice'),
        ),
    ]
