# Generated by Django 6.0.8 on 2026-09-22 13:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_order_custom_gst_rate_order_gst_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_alias',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Category Alias e.g. SCI, NAILCUTTER', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='closing_qty',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Closing Quantity / Current Stock', max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='group_alias',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Group Alias e.g. CUTLERY, SOLAR COMB', max_length=150),
        ),
        migrations.AddField(
            model_name='product',
            name='opening_qty',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Opening Quantity', max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, help_text='Uploaded product photo', null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(default='General', max_length=150),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
