# Generated by Django 6.0.8 on 2026-09-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_category_alias_product_closing_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.CharField(blank=True, default='', help_text='Selected product color variant', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.CharField(blank=True, default='', help_text='Available colors e.g. PL, GW, ALM, BKDC, TOM, ICE, SHELL, RG', max_length=255),
        ),
    ]
