# Generated by Django 6.0.8 on 2026-09-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_orderitem_color_product_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_images',
            field=models.JSONField(blank=True, default=dict, help_text='Mapping of color code to variant image URL'),
        ),
        migrations.AddField(
            model_name='product',
            name='gallery_images',
            field=models.JSONField(blank=True, default=list, help_text='Additional photo URLs or variant image paths'),
        ),
    ]
